"""Protocol for agent UI hosts (TUI, Telegram, future API chat)."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class AgentHost(Protocol):
    """Surface required by shared slash/command handlers."""

    agent: Any
    conversation_id: str
    profile: str
    streaming_enabled: bool
    _execution_modes: list[str]
    _execution_mode_index: int

    def transcript_write(self, content: Any) -> None: ...
    def run_worker(self, work: Any, **kwargs: Any) -> None: ...
    def _refresh_status_bar(self) -> None: ...

    def action_clear_chat(self) -> None: ...
    def action_help(self) -> None: ...
    def action_copy_output(self) -> None: ...
    def action_open_transcript(self) -> None: ...
    def copy_text(self, text: str, *, label: str = "copied") -> None: ...

    async def action_cycle_execution_mode(self, just_set: bool = False) -> None: ...
    def _action_stop_all(self) -> None: ...

    def _create_new_session(self) -> Any: ...
    def _show_sessions_list(self) -> Any: ...
    def _switch_to_session(self, index: int) -> Any: ...
    def _rename_current_session(self, name: str) -> None: ...
    def _get_available_profiles(self) -> list[str]: ...
    def _switch_profile(self, new_profile: str) -> Any: ...
    def _search_memory(self, query: str) -> Any: ...
    def _show_full_tool_result(self, index_from_end: int = 0) -> None: ...
    def _list_recent_tools(self) -> None: ...

    def _resolve_confirmation(self, choice: Any) -> None: ...
    def _resolve_plan_review(self, choice: Any, feedback: str = "") -> None: ...