"""Persist Telegram credentials for Helix CLI."""

from __future__ import annotations

import os
import re
from pathlib import Path

from cli.core import HELIX_HOME

TELEGRAM_ENV_PATH = HELIX_HOME / "telegram.env"
_TOKEN_RE = re.compile(r"^\d+:[A-Za-z0-9_-]{20,}$")


def ensure_helix_home() -> Path:
    from core.env_loader import init_helix_home

    return init_helix_home()


def load_telegram_env_files() -> None:
    """Load ~/.helix/.env (and project .env), then ~/.helix/telegram.env."""
    from core.env_loader import bootstrap_env

    bootstrap_env()

    try:
        from dotenv import load_dotenv
    except ImportError:
        return

    if TELEGRAM_ENV_PATH.is_file():
        load_dotenv(TELEGRAM_ENV_PATH, override=False)


def token_looks_valid(token: str) -> bool:
    return bool(_TOKEN_RE.match(token.strip()))


def mask_token(token: str) -> str:
    t = token.strip()
    if not t or ":" not in t:
        return "(not set)"
    bot_id, secret = t.split(":", 1)
    if len(secret) <= 8:
        return f"{bot_id}:***"
    return f"{bot_id}:{secret[:4]}…{secret[-4:]}"


def format_env_lines(values: dict[str, str]) -> str:
    lines = ["# Helix Telegram — generated by `helix telegram setup`", ""]
    order = (
        "TELEGRAM_BOT_TOKEN",
        "HELIX_TELEGRAM_ALLOWED_USERS",
        "HELIX_TELEGRAM_ALLOW_ALL",
        "HELIX_TELEGRAM_PROFILE",
        "HELIX_TELEGRAM_EDIT_MS",
    )
    written: set[str] = set()
    for key in order:
        if key in values and values[key]:
            lines.append(f"{key}={values[key]}")
            written.add(key)
    for key, val in sorted(values.items()):
        if key not in written and val:
            lines.append(f"{key}={val}")
    return "\n".join(lines) + "\n"


def save_telegram_env(values: dict[str, str]) -> Path:
    ensure_helix_home()
    TELEGRAM_ENV_PATH.write_text(format_env_lines(values), encoding="utf-8")
    apply_to_environ(values)
    return TELEGRAM_ENV_PATH


def apply_to_environ(values: dict[str, str]) -> None:
    for key, value in values.items():
        if value:
            os.environ[key] = value


def read_telegram_env_values() -> dict[str, str]:
    if not TELEGRAM_ENV_PATH.is_file():
        return {}
    out: dict[str, str] = {}
    for line in TELEGRAM_ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        out[key.strip()] = val.strip()
    return out


def merge_project_env(project_env: Path, values: dict[str, str]) -> None:
    """Upsert Telegram keys into a project .env file."""
    keys = set(values)
    existing: list[str] = []
    if project_env.is_file():
        existing = project_env.read_text(encoding="utf-8").splitlines()

    out: list[str] = []
    seen: set[str] = set()
    for line in existing:
        if not line.strip() or line.strip().startswith("#"):
            out.append(line)
            continue
        key, sep, _ = line.partition("=")
        key = key.strip()
        if key in keys:
            out.append(f"{key}={values[key]}")
            seen.add(key)
        else:
            out.append(line)

    for key, val in values.items():
        if key not in seen and val:
            if out and out[-1].strip():
                out.append("")
            out.append(f"{key}={val}")

    project_env.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")