"""Persist Telegram credentials per Holix profile."""

from __future__ import annotations

import os
import re
from pathlib import Path

from core.env_loader import active_profile_name, profile_dir_path

_TOKEN_RE = re.compile(r"^\d+:[A-Za-z0-9_-]{20,}$")

def telegram_env_path(profile: str | None = None) -> Path:
    name = (profile or active_profile_name()).strip() or "default"
    return profile_dir_path(name) / "telegram.env"


def legacy_telegram_env_path() -> Path:
    from core.env_loader import holix_home

    return holix_home() / "telegram.env"


# Backward-compatible alias for default profile.
TELEGRAM_ENV_PATH = telegram_env_path("default")


def ensure_holix_home() -> Path:
    from core.env_loader import init_holix_home

    return init_holix_home()


def _env_value_missing(key: str) -> bool:
    """True when *key* is unset or blank in ``os.environ``."""
    if key not in os.environ:
        return True
    return not str(os.environ.get(key, "")).strip()


def load_telegram_env_files(profile: str | None = None) -> None:
    """Load profile env, then profile ``telegram.env`` (legacy global as fallback)."""
    from core.env_loader import bootstrap_profile_env

    name = (profile or active_profile_name()).strip() or "default"
    try:
        from core.crypto.unlock_context import bootstrap_profile_unlock_from_env

        bootstrap_profile_unlock_from_env(name)
    except Exception:
        pass
    bootstrap_profile_env(name)

    try:
        from core.crypto.profile_files import dotenv_values_for_path
    except ImportError:
        return

    path = telegram_env_path(name)
    if path.is_file():
        for key, value in dotenv_values_for_path(path, profile=name).items():
            if value is not None and str(value).strip() and _env_value_missing(key):
                os.environ[key] = str(value)
        return

    legacy = legacy_telegram_env_path()
    if legacy.is_file():
        for key, value in dotenv_values_for_path(legacy).items():
            if value is not None and str(value).strip() and _env_value_missing(key):
                os.environ[key] = str(value)


def token_looks_valid(token: str) -> bool:
    return bool(_TOKEN_RE.match(token.strip()))


def mask_token(token: str) -> str:
    t = token.strip()
    if not t or ":" not in t:
        return "(not set)"
    bot_id, secret = t.split(":", 1)
    if len(secret) <= 8:
        return f"{bot_id}:***"
    return f"{bot_id}:{secret[:4]}…{secret[-4:]}"


def format_env_lines(values: dict[str, str]) -> str:
    lines = ["# Holix Telegram — generated by `holix telegram setup`", ""]
    order = (
        "TELEGRAM_BOT_TOKEN",
        "HOLIX_TELEGRAM_ACCESS_REQUESTS",
        "HOLIX_TELEGRAM_ALLOWED_USERS",
        "HOLIX_TELEGRAM_ADMIN_USER_ID",
        "HOLIX_TELEGRAM_ADMIN_PROFILE",
        "HOLIX_TELEGRAM_USER_PROFILES",
        "HOLIX_TELEGRAM_ALLOW_ALL",
        "HOLIX_TELEGRAM_EDIT_MS",
    )
    written: set[str] = set()
    for key in order:
        if key in values and values[key]:
            lines.append(f"{key}={values[key]}")
            written.add(key)
    for key, val in sorted(values.items()):
        if key not in written and val:
            lines.append(f"{key}={val}")
    return "\n".join(lines) + "\n"


def save_telegram_env(values: dict[str, str], profile: str | None = None) -> Path:
    name = (profile or values.get("HOLIX_TELEGRAM_PROFILE") or active_profile_name()).strip()
    name = name or "default"
    ensure_holix_home()
    path = telegram_env_path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    from core.crypto.profile_files import write_profile_file_text

    write_profile_file_text(path, format_env_lines(values), profile=name)
    apply_to_environ(values)
    return path


def apply_to_environ(values: dict[str, str]) -> None:
    for key, value in values.items():
        if value:
            os.environ[key] = value


def read_telegram_env_values(profile: str | None = None) -> dict[str, str]:
    name = (profile or active_profile_name()).strip() or "default"
    path = telegram_env_path(name)
    legacy = False
    if not path.is_file():
        path = legacy_telegram_env_path()
        legacy = True
    if not path.is_file():
        return {}
    try:
        from core.crypto.profile_files import dotenv_values_for_path
    except ImportError:
        return {}
    return {
        key: str(value).strip()
        for key, value in dotenv_values_for_path(
            path,
            profile=None if legacy else name,
        ).items()
        if value is not None and str(value).strip()
    }


def merge_project_env(project_env: Path, values: dict[str, str]) -> None:
    """Upsert Telegram keys into a project .env file."""
    keys = set(values)
    existing: list[str] = []
    if project_env.is_file():
        existing = project_env.read_text(encoding="utf-8").splitlines()

    out: list[str] = []
    seen: set[str] = set()
    for line in existing:
        if not line.strip() or line.strip().startswith("#"):
            out.append(line)
            continue
        key, sep, _ = line.partition("=")
        key = key.strip()
        if key in keys:
            out.append(f"{key}={values[key]}")
            seen.add(key)
        else:
            out.append(line)

    for key, val in values.items():
        if key not in seen and val:
            if out and out[-1].strip():
                out.append("")
            out.append(f"{key}={val}")

    project_env.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")