"""Scaffold drop-in agent extensions under the profile extensions folder."""

from __future__ import annotations

import json
from typing import Any

from core.extensions.control import profile_agent_extensions_dir, validate_extension_name

_AGENT_PY = '''"""Agent extension: {name} (generated by Holix — do not put code in core/)."""

from __future__ import annotations

from typing import Any

try:
    from holix_sdk.agent import SlashCommandSpec
    from core.extensions.agent_base import AgentExtensionBase
    from core.tools.base import BaseTool
except ImportError as e:  # pragma: no cover
    raise ImportError("This extension requires Holix + holix-sdk") from e


class _{classname}Tool(BaseTool):
    def __init__(self) -> None:
        super().__init__()
        self.name = "{tool_name}"
        self.description = "{tool_description}"
        self.risk_level = "no"
        self.parameters = {{
            "type": "object",
            "properties": {{
                "text": {{"type": "string", "description": "Input text"}},
            }},
            "required": ["text"],
        }}

    async def execute(self, text: str = "", **kwargs: Any) -> str:
        return f"[{name}] {{text}}"


class {classname}Extension(AgentExtensionBase):
    name = "{name}"
    version = "0.1.0"
    requires_holix = ">=0.1.21"
    description = "{description}"
    permissions = frozenset({{"tools"}})

    def default_settings(self) -> dict[str, Any]:
        return {{"enabled": True}}

    def register_tools(self, registry: Any, agent: Any) -> None:
        registry.register(_{classname}Tool())

    def register_slash_commands(self, commands: list[SlashCommandSpec]) -> None:
        commands.append(
            SlashCommandSpec(
                command="/{slash}",
                description="{description}",
            )
        )

    def augment_system_prompt(self, profile: str) -> str | None:
        return (
            "## Extension `{name}`\\n"
            "Tool `{tool_name}` is available. "
            "Disable via agent_extensions_control.yaml or settings if broken."
        )


def get_agent_extension() -> {classname}Extension:
    return {classname}Extension()
'''


def _classname(name: str) -> str:
    parts = [p for p in name.replace("-", "_").split("_") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts) or "Custom"


def create_agent_extension_scaffold(
    profile: str,
    name: str,
    *,
    description: str = "",
    overwrite: bool = False,
) -> dict[str, Any]:
    """Create ``~/.holix/profiles/<p>/extensions/<name>/agent.py`` (+ manifest)."""
    n = validate_extension_name(name)
    desc = (description or f"Agent extension {n}").strip()
    root = profile_agent_extensions_dir(profile) / n
    agent_py = root / "agent.py"
    if agent_py.is_file() and not overwrite:
        raise FileExistsError(f"extension already exists: {agent_py}")
    root.mkdir(parents=True, exist_ok=True)
    classname = _classname(n)
    slash = n.replace("_", "-")
    tool_name = f"{n}_tool"
    agent_py.write_text(
        _AGENT_PY.format(
            name=n,
            classname=classname,
            description=desc.replace('"', "'"),
            slash=slash,
            tool_name=tool_name,
            tool_description=f"Tool provided by agent extension {n}",
        ),
        encoding="utf-8",
    )
    manifest = {
        "id": n,
        "version": "0.1.0",
        "requires": {"holix": ">=0.1.21", "holix_sdk": ">=0.1.0"},
        "description": desc,
        "capabilities": ["agent"],
        "permissions": ["tools"],
    }
    (root / "holix.plugin.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (root / "settings.default.yaml").write_text(
        "enabled: true\n",
        encoding="utf-8",
    )
    readme = root / "README.md"
    readme.write_text(
        f"# {n}\n\n"
        f"{desc}\n\n"
        "Drop-in agent extension (profile-local). "
        "In **local** mode the agent hot-reloads after `manage_agent_extensions create`. "
        "Messenger multi-user bots do not create self-extensions.\n\n"
        f"- Disable: set `enabled: false` in extension settings, or\n"
        f"  `disabled: [{n}]` in `agent_extensions_control.yaml`\n"
        f"- Emergency: `HOLIX_AGENT_EXTENSIONS_OFF=1`\n",
        encoding="utf-8",
    )
    return {
        "name": n,
        "path": str(root.resolve()),
        "agent_py": str(agent_py.resolve()),
        "slash": f"/{slash}",
        "tool": tool_name,
        "note": "Local mode: hot-reload after create. Edit agent.py then action=reload.",
    }
