"""User message for `/init` — deep project analysis → `.holix/HOLIX.md`."""

from __future__ import annotations

from core.project.holix_md import HOLIX_MD_REL_PATH, ensure_holix_dir

HOLIX_MD_TEMPLATE = """# Project context (Holix)

> Generated by `/init`. Update when the codebase changes significantly.

## Overview
- Purpose:
- Primary users / consumers:
- Repository type (monorepo, service, library, …):

## Directory structure
```
(tree — annotate important folders)
```

## Technology stack
- Languages:
- Frameworks:
- Databases / queues / caches:
- Package managers & build tools:

## Architecture
- High-level diagram (text or mermaid):
- Main layers / bounded contexts:
- Entry points (CLI, HTTP, workers, …):

## REST / HTTP API (if applicable)
- Base URL / versioning:
- Auth:
- Route map (method, path, handler/module, purpose):
- Request/response patterns:

## Key modules & responsibilities
| Module / package | Role |
|------------------|------|

## Configuration & environment
- Config files:
- Required env vars:
- Secrets handling:

## Documentation index
| Path | What it describes |
|------|-------------------|

## Development workflow
- Install:
- Run locally:
- Test:
- Lint / format:

## Code conventions
- Style / lint rules:
- Naming patterns:
- Error handling / logging:
- Testing approach:

## Important files
| File | Why it matters |

## Notes & gotchas
- …
"""


def build_init_user_message() -> str:
    """Prompt sent to the agent when the user runs `/init`."""
    ensure_holix_dir()
    return f"""Run a **deep project onboarding** for the current working directory.

## Goal
Produce an exhaustive, accurate project handbook at **`{HOLIX_MD_REL_PATH}`** (overwrite or create).
Every future agent in this repo will rely on this file first.

## How to work
1. Use tools extensively: `list_directory` (recursive where needed), `read_file`, `run_terminal_command` for safe discovery (`find`, `tree`, `rg`, package manifests).
2. Read **all** relevant docs: README*, CONTRIBUTING*, docs/, OpenAPI/Swagger, architecture ADRs, `.env.example`, CI configs.
3. Map **folder structure** with short explanations.
4. Identify **architecture**: layers, DI, event flow, main binaries/services.
5. Document **REST/HTTP** (or GraphQL/gRPC): routes, controllers/handlers, middleware, auth, DTOs.
6. List **key modules**, public APIs, and dependencies between packages.
7. Capture **how to run, test, build, deploy** from real config files (not guesses).
8. Summarize **code style** (linters, formatters, patterns seen in code).
9. If something is unclear, inspect code until confident; mark unknowns explicitly in the doc.

## Output
- Write the final document with `write_file` to **`{HOLIX_MD_REL_PATH}`**.
- Use the structure below (fill every section; add subsections as needed).
- Be **detailed and specific** (file paths, module names, command examples).
- Do **not** skip API or data-layer documentation if the project has them.

## Required template
```markdown
{HOLIX_MD_TEMPLATE.strip()}
```

When finished, confirm the absolute path written and give a 5–10 line summary of what you captured.
"""