"""Built-in slash tokens that custom commands must not override."""

from __future__ import annotations

# First token after '/' for Holix built-ins (keep in sync with
# cli/shared/commands/registry.py — tests assert coverage).
RESERVED_SLASH_NAMES: frozenset[str] = frozenset(
    {
        "help",
        "h",
        "?",
        "status",
        "clear",
        "cls",
        "metrics",
        "compress",
        "forget",
        "init",
        "stream",
        "mode",
        "models",
        "model",
        "stop",
        "process-stop",
        "process",
        "new",
        "sessions",
        "switch",
        "session",
        "profile",
        "memory",
        "memory-clear",
        "last",
        "tools",
        "copy",
        "open",
        "view",
        "transcript",
        "yes",
        "no",
        "1",
        "2",
        "3",
        "4",
        "plan-confirm",
        "plan-auto",
        "plan-refine",
        "plan-reject",
        "mcp",
        "search",
        "hub",
        "plugins",
        "marketplace",
        "skill",
        "skills",
        "learn",
        "launch",
        "cron",
        "spec",
        "subagents",
        "subagent-types",
        "subagent-spawn",
        "subagent-result",
        "subagent-terminate",
        "lang",
        "commands",
        "exit",
        "quit",
        "q",
    }
)
